dz_list = [
# 提供 [ [输入加空格, 替换后文本],] 形式的 dz_list 则启用程序后可以自动替换
# 有两个相同的内容,以最后一个为准

# 例如 ["1",	"S010"], 表示当输入 "1" 的时候,替换为 "S010"
# 例如 ["1-4",	"S019"], 表示当输入 "1-4" 的时候,替换为 "S019"
# 例如 ["1-5",	"S018"], 表示当输入 "1-5" 的时候,替换为 "S018"

["1",	"S010"],
["1-4",	"S019"],
["1-5",	"S018"],
["1-6",	"S017"],
["1-7",	"S014"],
["1-8",	"S016"],
["1-9F",	"S000"],
["2",	"S002"],
["24",	"S003"],
["2-4",	"S009"],
["246",	"S008"],
["2468",	"S004"],
["24689",	"S022"],
["2-5",	"S011"],
["2-5",	"S015"],
["2-6",	"S012"],
["2-7",	"S013"],
["2-8",	"S001"],
["2-9",	"S021"],
["3-6",	"S020"],
["3-7",	"S023"],
["4",	"S005"],
["6",	"S006"],
["F",	"S007"],
]

ESC_KEY = 'ctrl+alt+q'